name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_unit:
    name: compile
    runs-on: ubuntu-latest
    steps:
      - uses: volta-cli/action@v1
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run tsc
  build:
    name: Build Klinge Website
    runs-on: ubuntu-latest
    steps:
      - uses: volta-cli/action@v1
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build